basiccrm/basiccrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basiccrm/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
]

basiccrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

basiccrm/client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE, verbose_name='Команда')
    name = models.CharField(max_length=255, verbose_name='Имя')
    email = models.EmailField()
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан в')
    modified_at = models.DateTimeField(auto_now=True, verbose_name='Изменен в')

    class Meta:
        ordering = ('name',)
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return self.name


class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE, verbose_name='Команда')
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE, verbose_name='Клиент')
    content = models.TextField(blank=True, null=True, verbose_name='Добавить комментарий')
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано в')

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.created_by.username


class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE, verbose_name='Команда')
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE, verbose_name='Клиент')
    file = models.FileField(upload_to='clientfiles', verbose_name='Файл')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан в')

    def __str__(self):
        return self.created_by.username

basiccrm/client/forms.py
from django import forms

from .models import Client, Comment, ClientFile


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description',)

    name = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Название',
        'class': 'bg-form'
    }))

    email = forms.CharField(label="", widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'bg-form'
    }))

    description = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Описание',
        'class': 'bg-form'
    }))


class AddCommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Добавить информацию',
        'class': 'bg-comment1'
    }))

    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

basiccrm/client/views.py
import csv

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .forms import AddClientForm, AddCommentForm, AddFileForm
from .models import Client

from team.models import Team


@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Client', 'Description', 'Created at', 'Created by'])

    for client in clients:
        writer.writerow([client.name, client.description, client.created_at, client.created_by])

    return response


@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)

    return render(request, 'client/clients_list.html', {
        'clients': clients
    })


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk
            file.created_by = request.user
            file.save()

            return redirect('clients:detail', pk=pk)
    return redirect('clients:detail', pk=pk)


@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
    else:
        form = AddCommentForm()

    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form': form,
        'fileform': AddFileForm(),
    })


@login_required
def clients_add(request):
    team = request.user.userprofile.active_team

    if request.method == 'POST':
        form = AddClientForm(request.POST)

        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, 'Клиент был создан.')

            return redirect('clients:list')
    else:
        form = AddClientForm()

    return render(request, 'client/clients_add.html', {
        'form': form,
        'team': team
    })


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

            messages.success(request, 'Изменения были сохранены.')

            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)

    return render(request, 'client/clients_edit.html', {
        'form': form
    })


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, 'Клиент был удален.')

    return redirect('clients:list')

basiccrm/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Добавить клиента{% endblock %}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="mt-4 mb-4 text-2xl font-bold text-dark">Добавить клиента</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="btn-edit">Отправить</button>
            </form>
        {% else %}
            <div class="mb-3 text-base font-semibold text-[#B45454]">
                Ваша команда достигла максимального количества клиентов.
            </div>
        {% endif %}
    </div>
{% endblock %}

basiccrm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <div class="container mx-auto text-base">


        <h1 class="mt-4 mb-4 text-3xl font-bold text-dark">{{ client.name }}</h1>

        <div class="mb-6 bg-comment" >

        {% if client.description %}
            <p class="font-semibold">Описание:</p>
            <p class="mb-2 ">{{ client.description }}</p>
        {% endif %}


        <p class="font-semibold">Создано: </p>
        <p class="mb-2 ">{{ client.created_at }}</p>

        <p class="font-semibold">Изменено:</p>
        <p class="mb-6">{{ client.modified_at }}</p>
        </div>


        <a href="{% url 'clients:edit' client.id %}" class="btn-edit">Редактировать</a>
        <a href="{% url 'clients:delete' client.id %}" class="btn-edit">Удалить</a>

        <hr class="mb-10 mt-10 my-4">

        <h2 class="mb-6 text-xl">Заметки</h2>

        <div class="mb-6 space-y-4">
            {% for comment in client.comments.all %}
                <div class="bg-comment">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> | {{ comment.created_at }}</p>
                    &quot; {{ comment.content }}	&quot;
                </div>
            {% endfor %}
        </div>

        <hr class="mb-10 mt-10 my-4">

<!--        <h2 class="mb-6 text-xl">Введите заметки</h2>-->

        <form method="post" action="{% url 'clients:add_comment' client.id %}"  >
            {% csrf_token %}

            {{ form.as_p }}

            <button class="mt-6 btn-edit">Отправить</button>

        </form>

        <hr class="mb-10 mt-10 my-4">

        <h2 class="mb-4 text-xl">Прикрепленные файлы</h2>

        <div class=" mb-6 space-y-4">
            {% for file in client.files.all %}
                <div class="bg-comment">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> | {{ file.created_at }}</p>

                    <a href="{{ file.file.url }}" target="_blank">&laquo; Скачать &raquo;</a>
                </div>
            {% endfor %}
        </div>
         <hr class="mb-10 mt-10 my-4">

        <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
            <div class="bg-comment1" >
                {% csrf_token %}

                {{ fileform.as_p }}
            </div>
            <button class="mt-6 btn-edit">Отправить</button>

        </form>

        <hr class=" mb-10 mt-10 my-4">

        <a href="{% url 'clients:list' %}">&lArr; Назад к клиентам</a>

    </div>
{% endblock %}

basiccrm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Редактировать клиента{% endblock%}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="mt-4 mb-4 text-2xl font-bold text-dark">Редактировать клиента</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="btn-edit">Отправить</button>
        </form>
    </div>
{% endblock %}

basiccrm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}Клиенты{% endblock%}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="mt-4 mb-4 text-3xl font-bold text-dark">Клиенты</h1>

        <a href="{% url 'clients:add' %}" class="btn-blue">Добавить клиента</a>
        <a href="{% url 'clients:export' %}" class="btn-edit">Экспорт клиентов</a>

        {% if clients %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 border-[1.5px] border-primary font-semibold w-full">Имя</p>
            </div>

            {% for client in clients %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray' '' %}">
                        <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">В базе данных пока нет клиентов...</p>
        {% endif %}
    </div>
{% endblock %}