basiccrm/basiccrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basiccrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

basiccrm/team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),
]

basiccrm/userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

basiccrm/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    active_team = models.ForeignKey(Team, related_name='userprofiles', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return f"{self.user}"

basiccrm/userprofile/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Ваш логин',
        'class': 'bg-forms'
    }))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={
        'placeholder': 'Ваш пароль',
        'class': 'bg-forms'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Ваш логин',
        'class': 'bg-forms'
    }))
    email = forms.CharField(label="", widget=forms.EmailInput(attrs={
        'placeholder': 'Ваш электронный адрес',
        'class': 'bg-forms'
    }))
    password1 = forms.CharField(label="", widget=forms.PasswordInput(attrs={
        'placeholder': 'Ваш пароль',
        'class': 'bg-forms'
    }))
    password2 = forms.CharField(label="", widget=forms.PasswordInput(attrs={
        'placeholder': 'Повторите пароль',
        'class': 'bg-forms'
    }))

basiccrm/userprofile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import SignupForm
from .models import Userprofile

from team.models import Team


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()

            team = Team.objects.create(name='Название команды', created_by=user)
            team.members.add(user)
            team.save()

            Userprofile.objects.create(user=user, active_team=team)

            return redirect('/log-in/')
    else:
        form = SignupForm()

    return render(request, 'userprofile/signup.html', {
        'form': form
    })


@login_required
def myaccount(request):
    return render(request, 'userprofile/myaccount.html')

basiccrm/userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Войти{% endblock%}

{% block content %}
<div class="bg-[#F4F7FF] py-20 lg:py-[120px]" xmlns="http://www.w3.org/1999/html">
  <div class="container mx-auto">
    <div class="-mx-4 flex flex-wrap">
      <div class="w-full px-4">
        <div class="relative mx-auto max-w-[525px] overflow-hidden rounded-lg bg-white py-16 px-10 text-center sm:px-12 md:px-[60px]">
          <div class="mb-10 text-center md:mb-16">
            <a href="{% url 'index' %}" class="mx-auto inline-block max-w-[160px]"><img src="{% static 'assets/images/logo/logo.svg' %}" alt="logo" /></a>
          </div>
          <form method="post" action=".">
              {% csrf_token %}

              {{ form.as_p }}
            <div class="mb-10">
              <button type="submit" class="bordder-primary w-full cursor-pointer rounded-md border bg-primary py-3 px-5 text-base text-white transition hover:bg-opacity-90">
                  Авторизоваться
              </button>
            </div>
          </form>
            <a href="#" class="mb-2 inline-block text-base text-[#adadad] hover:text-primary hover:underline">
            Забыли пароль?
            </a>
          <p class="text-base text-[#adadad]">
            Еще не зарегистрированы?
            <a href="{% url 'userprofile:signup' %}" class="text-primary hover:underline">Зарегистрироваться</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock%}

basiccrm/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<div class="container mx-auto">
    <h1 class="mb-6 text-xl">Профиль пользователя</h1>

    <p class="mb-2">
        <strong>Имя пользователя: </strong>{{ request.user.username }}
    </p>

    <p class="mb-2">
        {% if active_team %}
            <strong>Группа: </strong><a href="{% url 'team:detail' active_team.id %}">{{ active_team.name }}</a>

            {% if active_team.created_by == request.user %}
                <a href="{% url 'team:edit' active_team.id %}" >| &laquo; Редактировать &#187;</a>
            {% endif %}
        {% else %}
            <a href="{% url 'team:list' %}">Выберите команду</a>
        {% endif %}
    </p>

    <hr class="mb-4">

    <a href="{% url 'logout' %}" class="btn-red">Выйти из системы</a>
</div>
{% endblock %}

basiccrm/userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Зарегистрироваться{% endblock%}

{% block content %}
<!-- ====== Signup Section Start -->
<div class="bg-[#F4F7FF] py-20 lg:py-[120px]" xmlns="http://www.w3.org/1999/html">
  <div class="container mx-auto">
    <div class="-mx-4 flex flex-wrap">
      <div class="w-full px-4">
        <div class="relative mx-auto max-w-[525px] overflow-hidden rounded-lg bg-white py-16 px-10 text-center sm:px-12 md:px-[60px]">
          <div class="mb-10 text-center md:mb-16">
            <a href="{% url 'index' %}" class="mx-auto inline-block max-w-[160px]"><img src="{% static 'assets/images/logo/logo.svg' %}" alt="logo" /></a>
          </div>
          <form method="post" action=".">
              {% csrf_token %}

              {{ form.as_p }}
            <div class="mb-10">
              <button type="submit" class="bordder-primary w-full cursor-pointer rounded-md border bg-primary py-3 px-5 text-base text-white transition hover:bg-opacity-90">
                  Отправить
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ====== Signup Section End -->

{% endblock%}