basiccrm/basiccrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basiccrm/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
]

basiccrm/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.dashboard, name='index'),
]

basiccrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

basiccrm/team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),
]

basiccrm/userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

basiccrm/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

basiccrm/core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
    <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <link rel="shortcut icon" href="{% static 'assets/images/favicon.svg' %}" type="image/x-icon"/>

          <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">
          <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
          <script defer src="{% static 'assets/js/alpine.min.js' %}"></script>

          <title>{% block title %}{% endblock %}</title>
    </head>
    <body >
            {% include 'core/nav.html' %}
            {% if messages %}
                <div class="container mx-auto">
                    {% for message in messages %}
                        <div class="mb-11 flex w-full rounded-lg border-l-[6px] border-[#34D399] bg-[#34D399] bg-opacity-[15%] px-7 py-8 shadow-md md:p-9">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif%}

            {% block content %}
            {% endblock %}

            {% include 'core/footer.html' %}
    </body>
</html>

basiccrm/core/templates/core/nav.html
{% load static %}
<!--     ====== Navbar Section Start-->
<header
  x-data="
    {
      navbarOpen: false
    }
  "
  class="flex w-full items-center bg-white">
  <div class="container mx-auto">
    <div class="relative -mx-4 flex items-center justify-between">
      <div class="w-60 max-w-full px-4">
        <a href="{% url 'index' %}" class="block w-full py-5"><img src="{% static 'assets/images/logo/logo.svg' %}" alt="logo" class="w-full"/></a>
      </div>
      <div class="flex  items-center justify-between px-4">
        <div>
          <button
            @click="navbarOpen = !navbarOpen"
            :class="navbarOpen && 'navbarTogglerActive' " id="navbarToggler" class="absolute right-4 top-1/2 block -translate-y-1/2 rounded-lg px-3 py-[6px] ring-primary focus:ring-2 lg:hidden">
            <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
            <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
            <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
          </button>
          <nav  :class="!navbarOpen && 'hidden' " id="navbarCollapse" class="absolute right-4 top-full w-full max-w-[250px] rounded-lg bg-white py-5 px-6 shadow lg:static lg:block lg:w-full lg:max-w-full lg:shadow-none">
            <ul class="block lg:flex">
              <li>
                <a href="{% url 'about' %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">О нас</a>
              </li>
              {% if request.user.is_authenticated %}
              <li>
                <a href="{% url 'team:detail' active_team.id %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">{{ active_team.name }}</a>
              </li>
              <li>
                <a href="{% url 'dashboard:index' %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">Панель задач</a>
              </li>
              <li>
                <a href="{% url 'leads:list' %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">Заявки</a>
              </li>
              <li>
                <a href="{% url 'clients:list' %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">Клиенты</a>
              </li>
              <li>
                <a href="{% url 'userprofile:myaccount' %}" class="flex py-2 text-base font-medium text-dark hover:text-primary lg:ml-12 lg:inline-flex">Личный кабинет</a>
              </li>
            </ul>
          </nav>
        </div>
              {% else %}
          <div class="hidden justify-end pr-16 sm:flex lg:pr-0">
            <a href="{% url 'login' %}" class="py-2 px-7 text-base font-medium text-dark hover:text-primary">Войти</a>
            <a href="{% url 'userprofile:signup' %}" class="rounded-lg bg-primary py-2 px-7 text-base font-medium text-white hover:bg-opacity-90">Зарегистрироваться</a>
          </div>
              {% endif %}
      </div>
    </div>
  </div>
</header>