basiccrm/basiccrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basiccrm/lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

basiccrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Lead(models.Model):
    LOW = 'Низкий'
    MEDIUM = 'Средний'
    HIGH = 'Высокий'

    CHOICES_PRIORITY = (
        (LOW, 'Низкий'),
        (MEDIUM, 'Средний'),
        (HIGH, 'Высокий')
    )

    NEW = 'Открыта'
    CONTACTED = 'В работе'
    WON = 'Выполнена'
    LOST = 'Отклонена'

    CHOICES_STATUS = (
        (NEW, 'Открыта'),
        (CONTACTED, 'В работе'),
        (WON, 'Выполнена'),
        (LOST, 'Отклонена'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE, verbose_name='Команда')
    name = models.CharField(max_length=255, verbose_name='Имя')
    email = models.EmailField()
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM, verbose_name='Приоритет')
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW, verbose_name='Статус')
    converted_to_client = models.BooleanField(default=False, verbose_name='Конвертировать в клиента')
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE, verbose_name='Создана')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создана в')
    modified_at = models.DateTimeField(auto_now=True, verbose_name='Изменена в')

    class Meta:
        ordering = ('name',)
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"

    def __str__(self):
        return self.name


class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE, verbose_name='Команда')
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE, verbose_name='Заявка')
    file = models.FileField(upload_to='leadfiles', verbose_name='Файл')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE, verbose_name='Создан')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан в')

    class Meta:
        verbose_name = "Файл"
        verbose_name_plural = "Файлы"

    def __str__(self):
        return self.created_by.username


class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE, verbose_name='Команда')
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE, verbose_name='Заявка')
    content = models.TextField(blank=True, null=True, verbose_name='Описание')
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE, verbose_name='Создана')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создана в')

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.created_by.username

basiccrm/lead/forms.py
from django import forms

from .models import Lead, Comment, LeadFile


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)

    name = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Название',
        'class': 'bg-form'
    }))

    email = forms.CharField(label="", widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'bg-form'
    }))

    description = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Описание',
        'class': 'bg-form'
    }))


class AddCommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.TextInput(attrs={
        'placeholder': 'Добавить информацию',
        'class': 'bg-comment1'
    }))

    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

basiccrm/lead/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from .forms import AddCommentForm, AddFileForm
from .models import Lead

from client.models import Client, Comment as ClientComment
from team.models import Team


class LeadListView(LoginRequiredMixin, ListView):     # список заявок
    model = Lead

    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, converted_to_client=False)


class LeadDetailView(LoginRequiredMixin, DetailView):   # детали заявок
    model = Lead

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        context['fileform'] = AddFileForm()

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadDeleteView(LoginRequiredMixin, DeleteView):  # удалить заявку
    model = Lead
    success_url = reverse_lazy('leads:list')

    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class LeadUpdateView(LoginRequiredMixin, UpdateView):   # редактировать заявку
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактировать заявку'

        return context

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadCreateView(LoginRequiredMixin, CreateView):  # создать заявку
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status',)
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.request.user.userprofile.active_team
        context['team'] = team
        context['title'] = 'Добавить заявку'

        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.active_team
        self.object.save()

        return redirect(self.get_success_url())


class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = self.request.user.userprofile.active_team
            file.lead_id = pk
            file.created_by = request.user
            file.save()

        return redirect('leads:detail', pk=pk)


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = self.request.user.userprofile.active_team
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)


class ConvertToClientView(LoginRequiredMixin, View):   # добавить в потенциальные клиенты
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')

        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.active_team

        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team=team,
        )

        lead.converted_to_client = True
        lead.save()

        # Преобразовываем комментарии заявок в комментарии клиентов

        comments = lead.comments.all()

        for comment in comments:
            ClientComment.objects.create(
                client=client,
                content=comment.content,
                created_by=comment.created_by,
                team=team
            )

        # Показать сообщение перенаправить и сохранить сообщение

        messages.success(request, 'Заявка была добавлена к потенциальным клиентам .')

        return redirect('leads:list')

basiccrm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="mt-4 mb-4 text-3xl font-bold text-dark">{{ lead.name }}</h1>

        <div class="mb-6 bg-comment" >

        {% if lead.description %}
            <p class="font-semibold">Описание:</p>
            <p class="mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="font-semibold">Приоритет:</p>
        <p class="mb-2">{{ lead.get_priority_display }}</p>

        <p class="font-semibold">Статус:</p>
        <p class="mb-2">{{ lead.get_status_display }}</p>

        <p class="font-semibold">Время создания:</p>
        <p class="mb-2">{{ lead.created_at }}</p>

        <p class="font-semibold">Время обновления:</p>
        <p class="mb-6">{{ lead.modified_at }}</p>

        </div>


        <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
            {% csrf_token %}
        </form>

        <a href="{% url 'leads:convert' lead.id %}" class="btn-edit">Добавить клиента</a>
        <a href="{% url 'leads:edit' lead.id %}" class="btn-edit">Редактировать</a>
        <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="btn-edit">Удалить</a>

        <hr class="mb-10 mt-10 my-4">

        <h2 class="mb-6 text-xl">Примечания</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
                <div class="bg-comment">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>

                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <hr class="mb-10 mt-10 my-4">

<!--        <h2 class="mb-6 text-xl">Введите примечания</h2>-->

        <form method="post" action="{% url 'leads:add_comment' lead.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="mt-6 btn-edit">Отправить</button>

        </form>

        <hr class="mb-10 mt-10 my-4">

        <h2 class="mb-6 text-xl">Прикрепленные файлы</h2>

        <div class="mb-6 space-y-4">
            {% for file in lead.files.all %}
                <div class="bg-comment">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> | {{ file.created_at }}</p>

                    <a href="{{ file.file.url }}" target="_blank">&laquo; Скачать &raquo;</a>
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p }}

            <button class="mt-6 btn-edit">Отправить</button>

        </form>

        <hr class="my-4">

        <a href="{% url 'leads:list' %}">&lArr;  Назад к заявкам</a>
    </div>
{% endblock %}

basiccrm/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="text-xl">{{ title }}</h1>

        {% if team.plan.max_leads > team.leads.count or title == 'Редактировать заявку' %}
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="btn-edit">Отправить</button>
            </form>
        {% else %}
            <div class="mb-11 flex w-full rounded-lg border-l-[6px] border-[#F87171] bg-[#F87171] bg-opacity-[15%] px-7 py-8 shadow-md md:p-9">
                Ваша команда достигла максимального количества заявок.
            </div>
        {% endif %}
    </div>
{% endblock %}

basiccrm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Заявки{% endblock %}

{% block content %}
    <div class="container mx-auto text-base">
        <h1 class="mt-4 mb-4 text-3xl font-bold text-dark">Заявки</h1>

        <a href="{% url 'leads:add' %}" class="btn-blue">Добавить заявку</a>

        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray font-semibold w-full">Название</p>
                <p class="py-4 px-2 bg-gray font-semibold w-full">Приоритет</p>
                <p class="py-4 px-2 bg-gray font-semibold w-full">Статус</p>
            </div>

            {% for lead in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray' '' %}">
                        <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray' '' %}">{{ lead.get_status_display }}</p>
                </div>
            {% empty %}
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">В базе данных пока нет заявок ...</p>
        {% endif %}
    </div>
{% endblock %}